version: "3.9"

volumes:
  data:

services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      PG_HOST: db
    restart: unless-stopped

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped
